### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by killerdevildog11** [derhass/HelloCube#2]
rebuilding dependencies for glad/src/gl
rebuilding dependencies for HelloCube
g++ -Wall -Wno-comment -pthread -g -I glad/include -I glm/   -c -o HelloCube.o HelloCube.cpp
HelloCube.cpp: In function ‘bool initCubeApplication(CubeApp*, const AppConfig&)’:
HelloCube.cpp:835:36: error: too many arguments to function ‘int gladLoadGL()’
  835 |  if (!gladLoadGL(glfwGetProcAddress)) {
      |                                    ^
In file included from HelloCube.cpp:1:
/usr/include/glad/glad.h:693:11: note: declared here
  693 | GLAPI int gladLoadGL(void);
      |           ^~~~~~~~~~
make: *** [<builtin>: HelloCube.o] Error 1

**Comment by derhass** [comment]
> In file included from HelloCube.cpp:1:
> /usr/include/glad/glad.h:693:11: note: declared here

This is very weird. First of all, you seem to have installed a system-wide version of `glad`, which seems to be glad 1, while I'm using glad2 here, which do differ in the API. Having installed `glad` as a library doesn't really make much sense, because it is a code generator to generate a specific GL loader for one's particular needs, meant to be directly included into the source of the application (as I do).

However, the include paths should be setup up to correctly look for the local glad version deployed with this application, and it is right there in your compiler command line: `-I glad/include`.

Are you sure you are building the current version of the source code? Thing is, recent versions of glad2  have renamed the header file from `glad.h` to `gl.h`. There is not a single instance of `glad.h` in the whole source code anymore (in current master branch as well as quadbuffer_stereo branch). To me, this looks like you use a recent checkout, but your `HelloCube.cpp` still seems to have `#include <glad/glad.h>` instead of `#include <glad/gl.h>` at the first line. Since `glad.h` is gone in the local version, the compiler falls back to finding your system-wide glad1 headers.

**Comment by derhass** [comment]
Closing this as invalid. There's not a single mention of a `glad.h` in the current version at all.
